base_order_size: 0.01
macd_threshold: 0.002
macd_weight: 0.3
max_position_size: 0.1
momentum_period: 20
roc_threshold: 0.02
roc_weight: 0.4
rsi_overbought: 70
rsi_oversold: 30
rsi_period: 14
rsi_weight: 0.3
signal_threshold: 0.2
stop_loss_pct: 0.02
take_profit_pct: 0.04
volatility_multiplier: 1.0
volatility_scaling: true
